/**
 * Comprehensive India Administrative & Locality Dataset
 * Covers:
 * - All 36 States & Union Territories
 * - All Official Districts across India
 * - Prominent Sub-districts / Taluks / Tehsils across Karnataka & other states
 * - Major Cities, Localities, and Villages
 */

export interface IndianPlace {
  name: string;
  secondary: string;
  description: string;
  lat: number;
  lng: number;
  type: 'state' | 'district' | 'taluk' | 'city' | 'town' | 'village' | 'locality';
}

export const INDIA_ADMINISTRATIVE_PLACES: IndianPlace[] = [
  // --- STATES & UNION TERRITORIES (36) ---
  { name: 'Karnataka', secondary: 'State, India', description: 'Karnataka, India', lat: 15.3173, lng: 75.7139, type: 'state' },
  { name: 'Maharashtra', secondary: 'State, India', description: 'Maharashtra, India', lat: 19.7515, lng: 75.7139, type: 'state' },
  { name: 'Tamil Nadu', secondary: 'State, India', description: 'Tamil Nadu, India', lat: 11.1271, lng: 78.6569, type: 'state' },
  { name: 'Telangana', secondary: 'State, India', description: 'Telangana, India', lat: 18.1124, lng: 79.0193, type: 'state' },
  { name: 'Andhra Pradesh', secondary: 'State, India', description: 'Andhra Pradesh, India', lat: 15.9129, lng: 79.7400, type: 'state' },
  { name: 'Kerala', secondary: 'State, India', description: 'Kerala, India', lat: 10.8505, lng: 76.2711, type: 'state' },
  { name: 'Gujarat', secondary: 'State, India', description: 'Gujarat, India', lat: 22.2587, lng: 71.1924, type: 'state' },
  { name: 'Rajasthan', secondary: 'State, India', description: 'Rajasthan, India', lat: 27.0238, lng: 74.2179, type: 'state' },
  { name: 'Uttar Pradesh', secondary: 'State, India', description: 'Uttar Pradesh, India', lat: 26.8467, lng: 80.9462, type: 'state' },
  { name: 'Madhya Pradesh', secondary: 'State, India', description: 'Madhya Pradesh, India', lat: 22.9734, lng: 78.6569, type: 'state' },
  { name: 'West Bengal', secondary: 'State, India', description: 'West Bengal, India', lat: 22.9868, lng: 87.8550, type: 'state' },
  { name: 'Bihar', secondary: 'State, India', description: 'Bihar, India', lat: 25.0961, lng: 85.3131, type: 'state' },
  { name: 'Punjab', secondary: 'State, India', description: 'Punjab, India', lat: 31.1471, lng: 75.3412, type: 'state' },
  { name: 'Haryana', secondary: 'State, India', description: 'Haryana, India', lat: 29.0588, lng: 76.0856, type: 'state' },
  { name: 'Odisha', secondary: 'State, India', description: 'Odisha, India', lat: 20.9517, lng: 85.0985, type: 'state' },
  { name: 'Assam', secondary: 'State, India', description: 'Assam, India', lat: 26.2006, lng: 92.9376, type: 'state' },
  { name: 'Jharkhand', secondary: 'State, India', description: 'Jharkhand, India', lat: 23.6102, lng: 85.2799, type: 'state' },
  { name: 'Chhattisgarh', secondary: 'State, India', description: 'Chhattisgarh, India', lat: 21.2787, lng: 81.8661, type: 'state' },
  { name: 'Uttarakhand', secondary: 'State, India', description: 'Uttarakhand, India', lat: 30.0668, lng: 79.0193, type: 'state' },
  { name: 'Himachal Pradesh', secondary: 'State, India', description: 'Himachal Pradesh, India', lat: 31.1048, lng: 77.1734, type: 'state' },
  { name: 'Goa', secondary: 'State, India', description: 'Goa, India', lat: 15.2993, lng: 74.1240, type: 'state' },
  { name: 'Tripura', secondary: 'State, India', description: 'Tripura, India', lat: 23.9408, lng: 91.9882, type: 'state' },
  { name: 'Meghalaya', secondary: 'State, India', description: 'Meghalaya, India', lat: 25.4670, lng: 91.3662, type: 'state' },
  { name: 'Manipur', secondary: 'State, India', description: 'Manipur, India', lat: 24.6637, lng: 93.9063, type: 'state' },
  { name: 'Nagaland', secondary: 'State, India', description: 'Nagaland, India', lat: 26.1584, lng: 94.5624, type: 'state' },
  { name: 'Mizoram', secondary: 'State, India', description: 'Mizoram, India', lat: 23.1645, lng: 92.9376, type: 'state' },
  { name: 'Arunachal Pradesh', secondary: 'State, India', description: 'Arunachal Pradesh, India', lat: 28.2180, lng: 94.7278, type: 'state' },
  { name: 'Sikkim', secondary: 'State, India', description: 'Sikkim, India', lat: 27.5330, lng: 88.5122, type: 'state' },
  { name: 'Delhi', secondary: 'National Capital Territory, India', description: 'Delhi, India', lat: 28.7041, lng: 77.1025, type: 'state' },
  { name: 'Jammu and Kashmir', secondary: 'Union Territory, India', description: 'Jammu and Kashmir, India', lat: 33.7782, lng: 76.5762, type: 'state' },
  { name: 'Ladakh', secondary: 'Union Territory, India', description: 'Ladakh, India', lat: 34.1526, lng: 77.5771, type: 'state' },
  { name: 'Chandigarh', secondary: 'Union Territory, India', description: 'Chandigarh, India', lat: 30.7333, lng: 76.7794, type: 'state' },
  { name: 'Puducherry', secondary: 'Union Territory, India', description: 'Puducherry, India', lat: 11.9416, lng: 79.8083, type: 'state' },
  { name: 'Andaman and Nicobar Islands', secondary: 'Union Territory, India', description: 'Andaman and Nicobar Islands, India', lat: 11.7401, lng: 92.6586, type: 'state' },
  { name: 'Dadra and Nagar Haveli and Daman and Diu', secondary: 'Union Territory, India', description: 'Dadra and Nagar Haveli and Daman and Diu, India', lat: 20.4283, lng: 72.8397, type: 'state' },
  { name: 'Lakshadweep', secondary: 'Union Territory, India', description: 'Lakshadweep, India', lat: 10.5667, lng: 72.6417, type: 'state' },

  // --- KARNATAKA DISTRICTS & KEY TALUKS (31 Districts + Taluks) ---
  { name: 'Bengaluru Urban', secondary: 'District, Karnataka, India', description: 'Bengaluru Urban, Karnataka, India', lat: 12.9716, lng: 77.5946, type: 'district' },
  { name: 'Bengaluru Rural', secondary: 'District, Karnataka, India', description: 'Bengaluru Rural, Karnataka, India', lat: 13.2272, lng: 77.5768, type: 'district' },
  { name: 'Bagalkote', secondary: 'District, Karnataka, India', description: 'Bagalkote, Karnataka, India', lat: 16.1691, lng: 75.6615, type: 'district' },
  { name: 'Ballari', secondary: 'District, Karnataka, India', description: 'Ballari, Karnataka, India', lat: 15.1394, lng: 76.9214, type: 'district' },
  { name: 'Belagavi', secondary: 'District, Karnataka, India', description: 'Belagavi, Karnataka, India', lat: 15.8497, lng: 74.4977, type: 'district' },
  { name: 'Bidar', secondary: 'District, Karnataka, India', description: 'Bidar, Karnataka, India', lat: 17.9104, lng: 77.5199, type: 'district' },
  { name: 'Chamarajanagar', secondary: 'District, Karnataka, India', description: 'Chamarajanagar, Karnataka, India', lat: 11.9261, lng: 76.9437, type: 'district' },
  { name: 'Chikkaballapura', secondary: 'District, Karnataka, India', description: 'Chikkaballapura, Karnataka, India', lat: 13.4355, lng: 77.7315, type: 'district' },
  { name: 'Chikkamagaluru', secondary: 'District, Karnataka, India', description: 'Chikkamagaluru, Karnataka, India', lat: 13.3161, lng: 75.7720, type: 'district' },
  { name: 'Chitradurga', secondary: 'District, Karnataka, India', description: 'Chitradurga, Karnataka, India', lat: 14.2234, lng: 76.4005, type: 'district' },
  { name: 'Dakshina Kannada', secondary: 'District, Karnataka, India', description: 'Dakshina Kannada, Karnataka, India', lat: 12.8703, lng: 75.2429, type: 'district' },
  { name: 'Davanagere', secondary: 'District, Karnataka, India', description: 'Davanagere, Karnataka, India', lat: 14.4644, lng: 75.9218, type: 'district' },
  { name: 'Dharwad', secondary: 'District, Karnataka, India', description: 'Dharwad, Karnataka, India', lat: 15.4589, lng: 75.0078, type: 'district' },
  { name: 'Gadag', secondary: 'District, Karnataka, India', description: 'Gadag, Karnataka, India', lat: 15.4167, lng: 75.6333, type: 'district' },
  { name: 'Hassan', secondary: 'District, Karnataka, India', description: 'Hassan, Karnataka, India', lat: 13.0033, lng: 76.1004, type: 'district' },
  { name: 'Haveri', secondary: 'District, Karnataka, India', description: 'Haveri, Karnataka, India', lat: 14.7954, lng: 75.3991, type: 'district' },
  { name: 'Kalaburagi', secondary: 'District, Karnataka, India', description: 'Kalaburagi, Karnataka, India', lat: 17.3297, lng: 76.8343, type: 'district' },
  { name: 'Kodagu', secondary: 'District, Karnataka, India', description: 'Kodagu, Karnataka, India', lat: 12.3375, lng: 75.8069, type: 'district' },
  { name: 'Kolar', secondary: 'District, Karnataka, India', description: 'Kolar, Karnataka, India', lat: 13.1367, lng: 78.1291, type: 'district' },
  { name: 'Koppal', secondary: 'District, Karnataka, India', description: 'Koppal, Karnataka, India', lat: 15.3456, lng: 76.1554, type: 'district' },
  { name: 'Mandya', secondary: 'District, Karnataka, India', description: 'Mandya, Karnataka, India', lat: 12.5218, lng: 76.8951, type: 'district' },
  { name: 'Mysuru', secondary: 'District, Karnataka, India', description: 'Mysuru, Karnataka, India', lat: 12.2958, lng: 76.6394, type: 'district' },
  { name: 'Raichur', secondary: 'District, Karnataka, India', description: 'Raichur, Karnataka, India', lat: 16.2120, lng: 77.3439, type: 'district' },
  { name: 'Ramanagara', secondary: 'District, Karnataka, India', description: 'Ramanagara, Karnataka, India', lat: 12.7150, lng: 77.2810, type: 'district' },
  { name: 'Shivamogga', secondary: 'District, Karnataka, India', description: 'Shivamogga, Karnataka, India', lat: 13.9299, lng: 75.5681, type: 'district' },
  { name: 'Shimoga', secondary: 'Shivamogga District, Karnataka, India', description: 'Shimoga, Karnataka, India', lat: 13.9299, lng: 75.5681, type: 'district' },
  { name: 'Tumakuru', secondary: 'District, Karnataka, India', description: 'Tumakuru, Karnataka, India', lat: 13.3409, lng: 77.1010, type: 'district' },
  { name: 'Udupi', secondary: 'District, Karnataka, India', description: 'Udupi, Karnataka, India', lat: 13.3409, lng: 74.7421, type: 'district' },
  { name: 'Uttara Kannada', secondary: 'District, Karnataka, India', description: 'Uttara Kannada, Karnataka, India', lat: 14.8136, lng: 74.1298, type: 'district' },
  { name: 'Vijayapura', secondary: 'District, Karnataka, India', description: 'Vijayapura, Karnataka, India', lat: 16.8302, lng: 75.7100, type: 'district' },
  { name: 'Yadgir', secondary: 'District, Karnataka, India', description: 'Yadgir, Karnataka, India', lat: 16.7622, lng: 77.1378, type: 'district' },
  { name: 'Vijayanagara', secondary: 'District, Karnataka, India', description: 'Vijayanagara, Karnataka, India', lat: 15.2715, lng: 76.3892, type: 'district' },

  // Key Taluks & Towns in Karnataka
  { name: 'Karwar', secondary: 'Uttara Kannada, Karnataka, India', description: 'Karwar, Uttara Kannada, Karnataka', lat: 14.8136, lng: 74.1298, type: 'taluk' },
  { name: 'Aland', secondary: 'Kalaburagi, Karnataka, India', description: 'Aland, Kalaburagi, Karnataka', lat: 17.5647, lng: 76.5684, type: 'taluk' },
  { name: 'Nelamangala', secondary: 'Bengaluru Rural, Karnataka, India', description: 'Nelamangala, Bengaluru Rural, Karnataka', lat: 13.0982, lng: 77.3916, type: 'taluk' },
  { name: 'Yelahanka', secondary: 'Bengaluru Urban, Karnataka, India', description: 'Yelahanka, Bengaluru Urban, Karnataka', lat: 13.1007, lng: 77.5963, type: 'taluk' },
  { name: 'Chikkabanavara', secondary: 'Bengaluru, Karnataka, India', description: 'Chikkabanavara, Bengaluru, Karnataka', lat: 13.0827, lng: 77.5097, type: 'locality' },
  { name: 'Soladevanahalli', secondary: 'Bengaluru, Karnataka, India', description: 'Soladevanahalli, Bengaluru, Karnataka', lat: 13.09074, lng: 77.48805, type: 'village' },
  { name: 'Soladevanahalli Police Station', secondary: 'Bengaluru, Karnataka, India', description: 'Soladevanahalli Police Station, Bengaluru, Karnataka', lat: 13.0885, lng: 77.4892, type: 'locality' },
  { name: 'Soladevanahalli Railway Station', secondary: 'Bengaluru, Karnataka, India', description: 'Soladevanahalli Railway Station, Bengaluru, Karnataka', lat: 13.0850, lng: 77.4870, type: 'locality' },
  { name: 'Hurali Chikkanahalli', secondary: 'Yelahanka, Bengaluru, Karnataka, India', description: 'Hurali Chikkanahalli, Bengaluru, Karnataka', lat: 13.1155, lng: 77.4837, type: 'village' },
  { name: 'Hebbal', secondary: 'Bengaluru, Karnataka, India', description: 'Hebbal, Bengaluru, Karnataka', lat: 13.0358, lng: 77.5970, type: 'locality' },
  { name: 'Koramangala', secondary: 'Bengaluru, Karnataka, India', description: 'Koramangala, Bengaluru, Karnataka', lat: 12.9352, lng: 77.6245, type: 'locality' },
  { name: 'Indiranagar', secondary: 'Bengaluru, Karnataka, India', description: 'Indiranagar, Bengaluru, Karnataka', lat: 12.9784, lng: 77.6408, type: 'locality' },
  { name: 'Whitefield', secondary: 'Bengaluru, Karnataka, India', description: 'Whitefield, Bengaluru, Karnataka', lat: 12.9698, lng: 77.7500, type: 'locality' },
  { name: 'Jayanagar', secondary: 'Bengaluru, Karnataka, India', description: 'Jayanagar, Bengaluru, Karnataka', lat: 12.9308, lng: 77.5838, type: 'locality' },
  { name: 'HSR Layout', secondary: 'Bengaluru, Karnataka, India', description: 'HSR Layout, Bengaluru, Karnataka', lat: 12.9121, lng: 77.6446, type: 'locality' },
  { name: 'BTM Layout', secondary: 'Bengaluru, Karnataka, India', description: 'BTM Layout, Bengaluru, Karnataka', lat: 12.9166, lng: 77.6101, type: 'locality' },
  { name: 'Electronic City', secondary: 'Bengaluru, Karnataka, India', description: 'Electronic City, Bengaluru, Karnataka', lat: 12.8452, lng: 77.6602, type: 'locality' },
  { name: 'Rajajinagar', secondary: 'Bengaluru, Karnataka, India', description: 'Rajajinagar, Bengaluru, Karnataka', lat: 12.9982, lng: 77.5530, type: 'locality' },
  { name: 'Malleshwaram', secondary: 'Bengaluru, Karnataka, India', description: 'Malleshwaram, Bengaluru, Karnataka', lat: 13.0031, lng: 77.5643, type: 'locality' },
  { name: 'Peenya', secondary: 'Bengaluru, Karnataka, India', description: 'Peenya, Bengaluru, Karnataka', lat: 13.0285, lng: 77.5197, type: 'locality' },
  { name: 'Jalahalli', secondary: 'Bengaluru, Karnataka, India', description: 'Jalahalli, Bengaluru, Karnataka', lat: 13.0526, lng: 77.5456, type: 'locality' },
  { name: 'Yeshwanthpur', secondary: 'Bengaluru, Karnataka, India', description: 'Yeshwanthpur, Bengaluru, Karnataka', lat: 13.0238, lng: 77.5529, type: 'locality' },
  { name: 'Vidyaranyapura', secondary: 'Bengaluru, Karnataka, India', description: 'Vidyaranyapura, Bengaluru, Karnataka', lat: 13.0782, lng: 77.5583, type: 'locality' },
  { name: 'Dasarahalli', secondary: 'Bengaluru, Karnataka, India', description: 'Dasarahalli, Bengaluru, Karnataka', lat: 13.0471, lng: 77.5126, type: 'locality' },
  { name: 'Banashankari', secondary: 'Bengaluru, Karnataka, India', description: 'Banashankari, Bengaluru, Karnataka', lat: 12.9255, lng: 77.5468, type: 'locality' },
  { name: 'Basavanagudi', secondary: 'Bengaluru, Karnataka, India', description: 'Basavanagudi, Bengaluru, Karnataka', lat: 12.9422, lng: 77.5753, type: 'locality' },
  { name: 'Marathahalli', secondary: 'Bengaluru, Karnataka, India', description: 'Marathahalli, Bengaluru, Karnataka', lat: 12.9591, lng: 77.6974, type: 'locality' },
  { name: 'Bellandur', secondary: 'Bengaluru, Karnataka, India', description: 'Bellandur, Bengaluru, Karnataka', lat: 12.9260, lng: 77.6762, type: 'locality' },
  { name: 'Hesaraghatta', secondary: 'Bengaluru, Karnataka, India', description: 'Hesaraghatta, Bengaluru, Karnataka', lat: 13.1368, lng: 77.4859, type: 'locality' },
  { name: 'Karkala', secondary: 'Udupi, Karnataka, India', description: 'Karkala, Udupi, Karnataka, India', lat: 13.2148, lng: 74.9961, type: 'taluk' },
  { name: 'Gauribidanur', secondary: 'Chikkaballapura, Karnataka, India', description: 'Gauribidanur, Chikkaballapura, Karnataka', lat: 13.6135, lng: 77.5131, type: 'taluk' },
  { name: 'Alur', secondary: 'Hassan, Karnataka, India', description: 'Alur, Hassan, Karnataka, India', lat: 12.9856, lng: 75.9862, type: 'taluk' },
  { name: 'Hubballi', secondary: 'Dharwad, Karnataka, India', description: 'Hubballi, Karnataka, India', lat: 15.3647, lng: 75.1240, type: 'city' },
  { name: 'Mangaluru', secondary: 'Dakshina Kannada, Karnataka, India', description: 'Mangaluru, Karnataka, India', lat: 12.9141, lng: 74.8560, type: 'city' },
  { name: 'Doddaballapura', secondary: 'Bengaluru Rural, Karnataka, India', description: 'Doddaballapura, Karnataka, India', lat: 13.2929, lng: 77.5430, type: 'taluk' },
  { name: 'Hoskote', secondary: 'Bengaluru Rural, Karnataka, India', description: 'Hoskote, Karnataka, India', lat: 13.0699, lng: 77.7981, type: 'taluk' },
  { name: 'Anekal', secondary: 'Bengaluru Urban, Karnataka, India', description: 'Anekal, Karnataka, India', lat: 12.7107, lng: 77.6974, type: 'taluk' },
  { name: 'Channapatna', secondary: 'Ramanagara, Karnataka, India', description: 'Channapatna, Karnataka, India', lat: 12.6518, lng: 77.2089, type: 'taluk' },
  { name: 'Kanakapura', secondary: 'Ramanagara, Karnataka, India', description: 'Kanakapura, Karnataka, India', lat: 12.5461, lng: 77.4194, type: 'taluk' },
  { name: 'Magadi', secondary: 'Ramanagara, Karnataka, India', description: 'Magadi, Karnataka, India', lat: 12.9566, lng: 77.2307, type: 'taluk' },
  { name: 'Kunigal', secondary: 'Tumakuru, Karnataka, India', description: 'Kunigal, Karnataka, India', lat: 13.0247, lng: 77.0347, type: 'taluk' },
  { name: 'Tiptur', secondary: 'Tumakuru, Karnataka, India', description: 'Tiptur, Karnataka, India', lat: 13.2570, lng: 76.4777, type: 'taluk' },
  { name: 'Sira', secondary: 'Tumakuru, Karnataka, India', description: 'Sira, Karnataka, India', lat: 13.7449, lng: 76.9048, type: 'taluk' },
  { name: 'Gokak', secondary: 'Belagavi, Karnataka, India', description: 'Gokak, Karnataka, India', lat: 16.1667, lng: 74.8333, type: 'taluk' },
  { name: 'Chikkodi', secondary: 'Belagavi, Karnataka, India', description: 'Chikkodi, Karnataka, India', lat: 16.4300, lng: 74.5900, type: 'taluk' },
  { name: 'Sirsi', secondary: 'Uttara Kannada, Karnataka, India', description: 'Sirsi, Karnataka, India', lat: 14.6195, lng: 74.8354, type: 'taluk' },
  { name: 'Bhatkal', secondary: 'Uttara Kannada, Karnataka, India', description: 'Bhatkal, Karnataka, India', lat: 13.9774, lng: 74.5539, type: 'taluk' },
  { name: 'Kumta', secondary: 'Uttara Kannada, Karnataka, India', description: 'Kumta, Karnataka, India', lat: 14.4267, lng: 74.4089, type: 'taluk' },
  { name: 'Dandeli', secondary: 'Uttara Kannada, Karnataka, India', description: 'Dandeli, Karnataka, India', lat: 15.2361, lng: 74.6173, type: 'taluk' },
  { name: 'Kundapura', secondary: 'Udupi, Karnataka, India', description: 'Kundapura, Karnataka, India', lat: 13.6268, lng: 74.6914, type: 'taluk' },
  { name: 'Puttur', secondary: 'Dakshina Kannada, Karnataka, India', description: 'Puttur, Karnataka, India', lat: 12.7667, lng: 75.2000, type: 'taluk' },
  { name: 'Bantwal', secondary: 'Dakshina Kannada, Karnataka, India', description: 'Bantwal, Karnataka, India', lat: 12.8906, lng: 75.0345, type: 'taluk' },
  { name: 'Sullia', secondary: 'Dakshina Kannada, Karnataka, India', description: 'Sullia, Karnataka, India', lat: 12.5600, lng: 75.3900, type: 'taluk' },
  { name: 'Belthangady', secondary: 'Dakshina Kannada, Karnataka, India', description: 'Belthangady, Karnataka, India', lat: 13.0000, lng: 75.3000, type: 'taluk' },
  { name: 'Madikeri', secondary: 'Kodagu, Karnataka, India', description: 'Madikeri, Karnataka, India', lat: 12.4244, lng: 75.7382, type: 'taluk' },
  { name: 'Somwarpet', secondary: 'Kodagu, Karnataka, India', description: 'Somwarpet, Karnataka, India', lat: 12.6000, lng: 75.8700, type: 'taluk' },
  { name: 'Virajpet', secondary: 'Kodagu, Karnataka, India', description: 'Virajpet, Karnataka, India', lat: 12.2000, lng: 75.8000, type: 'taluk' },
  { name: 'Nanjangud', secondary: 'Mysuru, Karnataka, India', description: 'Nanjangud, Karnataka, India', lat: 12.1190, lng: 76.6811, type: 'taluk' },
  { name: 'Hunsur', secondary: 'Mysuru, Karnataka, India', description: 'Hunsur, Karnataka, India', lat: 12.3080, lng: 76.2903, type: 'taluk' },
  { name: 'Kollegal', secondary: 'Chamarajanagar, Karnataka, India', description: 'Kollegal, Karnataka, India', lat: 12.1557, lng: 77.1147, type: 'taluk' },
  { name: 'Gundlupet', secondary: 'Chamarajanagar, Karnataka, India', description: 'Gundlupet, Karnataka, India', lat: 11.8000, lng: 76.6800, type: 'taluk' },
  { name: 'Srirangapatna', secondary: 'Mandya, Karnataka, India', description: 'Srirangapatna, Karnataka, India', lat: 12.4184, lng: 76.6947, type: 'taluk' },
  { name: 'Maddur', secondary: 'Mandya, Karnataka, India', description: 'Maddur, Karnataka, India', lat: 12.5842, lng: 77.0450, type: 'taluk' },
  { name: 'Malavalli', secondary: 'Mandya, Karnataka, India', description: 'Malavalli, Karnataka, India', lat: 12.3800, lng: 77.0600, type: 'taluk' },
  { name: 'Nagamangala', secondary: 'Mandya, Karnataka, India', description: 'Nagamangala, Karnataka, India', lat: 12.8200, lng: 76.7600, type: 'taluk' },
  { name: 'KR Pet', secondary: 'Mandya, Karnataka, India', description: 'KR Pet, Mandya, Karnataka, India', lat: 12.6600, lng: 76.4900, type: 'taluk' },
  { name: 'Channarayapatna', secondary: 'Hassan, Karnataka, India', description: 'Channarayapatna, Karnataka, India', lat: 12.9000, lng: 76.3900, type: 'taluk' },
  { name: 'Arsikere', secondary: 'Hassan, Karnataka, India', description: 'Arsikere, Karnataka, India', lat: 13.3100, lng: 76.2600, type: 'taluk' },
  { name: 'Holenarasipura', secondary: 'Hassan, Karnataka, India', description: 'Holenarasipura, Karnataka, India', lat: 12.7900, lng: 76.2400, type: 'taluk' },
  { name: 'Sakleshpur', secondary: 'Hassan, Karnataka, India', description: 'Sakleshpur, Karnataka, India', lat: 12.9700, lng: 75.7800, type: 'taluk' },
  { name: 'Belur', secondary: 'Hassan, Karnataka, India', description: 'Belur, Karnataka, India', lat: 13.1600, lng: 75.8600, type: 'taluk' },
  { name: 'Bhadravati', secondary: 'Shivamogga, Karnataka, India', description: 'Bhadravati, Karnataka, India', lat: 13.8400, lng: 75.7000, type: 'taluk' },
  { name: 'Sagara', secondary: 'Shivamogga, Karnataka, India', description: 'Sagara, Karnataka, India', lat: 14.1600, lng: 75.0300, type: 'taluk' },
  { name: 'Shikaripura', secondary: 'Shivamogga, Karnataka, India', description: 'Shikaripura, Karnataka, India', lat: 14.2700, lng: 75.3500, type: 'taluk' },
  { name: 'Soraba', secondary: 'Shivamogga, Karnataka, India', description: 'Soraba, Karnataka, India', lat: 14.3800, lng: 75.0900, type: 'taluk' },
  { name: 'Thirthahalli', secondary: 'Shivamogga, Karnataka, India', description: 'Thirthahalli, Karnataka, India', lat: 13.6900, lng: 75.2400, type: 'taluk' },
  { name: 'Hosanagara', secondary: 'Shivamogga, Karnataka, India', description: 'Hosanagara, Karnataka, India', lat: 13.9200, lng: 75.0700, type: 'taluk' },
  { name: 'Harihara', secondary: 'Davanagere, Karnataka, India', description: 'Harihara, Karnataka, India', lat: 14.5100, lng: 75.8000, type: 'taluk' },
  { name: 'Channagiri', secondary: 'Davanagere, Karnataka, India', description: 'Channagiri, Karnataka, India', lat: 14.0200, lng: 75.9300, type: 'taluk' },
  { name: 'Honnali', secondary: 'Davanagere, Karnataka, India', description: 'Honnali, Karnataka, India', lat: 14.2400, lng: 75.6400, type: 'taluk' },
  { name: 'Hiriyur', secondary: 'Chitradurga, Karnataka, India', description: 'Hiriyur, Karnataka, India', lat: 13.9500, lng: 76.6200, type: 'taluk' },
  { name: 'Hosadurga', secondary: 'Chitradurga, Karnataka, India', description: 'Hosadurga, Karnataka, India', lat: 13.8000, lng: 76.2900, type: 'taluk' },
  { name: 'Holalkere', secondary: 'Chitradurga, Karnataka, India', description: 'Holalkere, Karnataka, India', lat: 14.0300, lng: 76.1900, type: 'taluk' },
  { name: 'Challakere', secondary: 'Chitradurga, Karnataka, India', description: 'Challakere, Karnataka, India', lat: 14.3100, lng: 76.6500, type: 'taluk' },
  { name: 'Gangavathi', secondary: 'Koppal, Karnataka, India', description: 'Gangavathi, Karnataka, India', lat: 15.4300, lng: 76.5300, type: 'taluk' },
  { name: 'Kushtagi', secondary: 'Koppal, Karnataka, India', description: 'Kushtagi, Karnataka, India', lat: 15.7500, lng: 76.2000, type: 'taluk' },
  { name: 'Yelburga', secondary: 'Koppal, Karnataka, India', description: 'Yelburga, Karnataka, India', lat: 15.6100, lng: 76.0100, type: 'taluk' },
  { name: 'Sindhanur', secondary: 'Raichur, Karnataka, India', description: 'Sindhanur, Karnataka, India', lat: 15.7700, lng: 76.7600, type: 'taluk' },
  { name: 'Manvi', secondary: 'Raichur, Karnataka, India', description: 'Manvi, Karnataka, India', lat: 15.9900, lng: 77.0500, type: 'taluk' },
  { name: 'Lingasugur', secondary: 'Raichur, Karnataka, India', description: 'Lingasugur, Karnataka, India', lat: 16.1600, lng: 76.5200, type: 'taluk' },
  { name: 'Devadurga', secondary: 'Raichur, Karnataka, India', description: 'Devadurga, Karnataka, India', lat: 16.4200, lng: 76.9300, type: 'taluk' },
  { name: 'Hospet', secondary: 'Vijayanagara, Karnataka, India', description: 'Hospet, Vijayanagara, Karnataka, India', lat: 15.2689, lng: 76.3909, type: 'taluk' },
  { name: 'Hampi', secondary: 'Vijayanagara, Karnataka, India', description: 'Hampi, Karnataka, India', lat: 15.3350, lng: 76.4600, type: 'village' },
  { name: 'Harapanahalli', secondary: 'Vijayanagara, Karnataka, India', description: 'Harapanahalli, Karnataka, India', lat: 14.8000, lng: 75.9900, type: 'taluk' },
  { name: 'Kudligi', secondary: 'Vijayanagara, Karnataka, India', description: 'Kudligi, Karnataka, India', lat: 14.9000, lng: 76.3800, type: 'taluk' },
  { name: 'Hagaribommanahalli', secondary: 'Vijayanagara, Karnataka, India', description: 'Hagaribommanahalli, Karnataka, India', lat: 15.0900, lng: 76.2000, type: 'taluk' },
  { name: 'Hadagali', secondary: 'Vijayanagara, Karnataka, India', description: 'Hadagali, Karnataka, India', lat: 15.0200, lng: 75.9600, type: 'taluk' },
  { name: 'Sandur', secondary: 'Ballari, Karnataka, India', description: 'Sandur, Karnataka, India', lat: 15.0900, lng: 76.5500, type: 'taluk' },
  { name: 'Siruguppa', secondary: 'Ballari, Karnataka, India', description: 'Siruguppa, Karnataka, India', lat: 15.6300, lng: 76.8900, type: 'taluk' },
  { name: 'Sedam', secondary: 'Kalaburagi, Karnataka, India', description: 'Sedam, Karnataka, India', lat: 17.1800, lng: 77.2900, type: 'taluk' },
  { name: 'Chittapur', secondary: 'Kalaburagi, Karnataka, India', description: 'Chittapur, Karnataka, India', lat: 17.1200, lng: 77.0800, type: 'taluk' },
  { name: 'Afzalpur', secondary: 'Kalaburagi, Karnataka, India', description: 'Afzalpur, Karnataka, India', lat: 17.2000, lng: 76.3500, type: 'taluk' },
  { name: 'Jevargi', secondary: 'Kalaburagi, Karnataka, India', description: 'Jevargi, Karnataka, India', lat: 17.0200, lng: 76.7700, type: 'taluk' },
  { name: 'Chincholi', secondary: 'Kalaburagi, Karnataka, India', description: 'Chincholi, Karnataka, India', lat: 17.4700, lng: 77.4300, type: 'taluk' },
  { name: 'Shorapur', secondary: 'Yadgir, Karnataka, India', description: 'Shorapur, Karnataka, India', lat: 16.5200, lng: 76.7600, type: 'taluk' },
  { name: 'Shahapur', secondary: 'Yadgir, Karnataka, India', description: 'Shahapur, Karnataka, India', lat: 16.7000, lng: 76.8400, type: 'taluk' },
  { name: 'Humnabad', secondary: 'Bidar, Karnataka, India', description: 'Humnabad, Karnataka, India', lat: 17.7700, lng: 77.1300, type: 'taluk' },
  { name: 'Bhalki', secondary: 'Bidar, Karnataka, India', description: 'Bhalki, Karnataka, India', lat: 18.0400, lng: 77.2100, type: 'taluk' },
  { name: 'Basavakalyan', secondary: 'Bidar, Karnataka, India', description: 'Basavakalyan, Karnataka, India', lat: 17.8700, lng: 76.9500, type: 'taluk' },
  { name: 'Aurad', secondary: 'Bidar, Karnataka, India', description: 'Aurad, Karnataka, India', lat: 18.2500, lng: 77.4300, type: 'taluk' },
  { name: 'Jamkhandi', secondary: 'Bagalkote, Karnataka, India', description: 'Jamkhandi, Karnataka, India', lat: 16.5100, lng: 75.2900, type: 'taluk' },
  { name: 'Mudhol', secondary: 'Bagalkote, Karnataka, India', description: 'Mudhol, Karnataka, India', lat: 16.3400, lng: 75.2800, type: 'taluk' },
  { name: 'Badami', secondary: 'Bagalkote, Karnataka, India', description: 'Badami, Karnataka, India', lat: 15.9200, lng: 75.6800, type: 'taluk' },
  { name: 'Hungund', secondary: 'Bagalkote, Karnataka, India', description: 'Hungund, Karnataka, India', lat: 16.0600, lng: 76.0600, type: 'taluk' },
  { name: 'Ilkal', secondary: 'Bagalkote, Karnataka, India', description: 'Ilkal, Karnataka, India', lat: 15.9600, lng: 76.1200, type: 'town' },
  { name: 'Bilagi', secondary: 'Bagalkote, Karnataka, India', description: 'Bilagi, Karnataka, India', lat: 16.3500, lng: 75.6200, type: 'taluk' },
  { name: 'Indi', secondary: 'Vijayapura, Karnataka, India', description: 'Indi, Karnataka, India', lat: 17.1700, lng: 75.9600, type: 'taluk' },
  { name: 'Sindagi', secondary: 'Vijayapura, Karnataka, India', description: 'Sindagi, Karnataka, India', lat: 16.9200, lng: 76.2300, type: 'taluk' },
  { name: 'Muddebihal', secondary: 'Vijayapura, Karnataka, India', description: 'Muddebihal, Karnataka, India', lat: 16.3400, lng: 76.1300, type: 'taluk' },
  { name: 'Basavana Bagewadi', secondary: 'Vijayapura, Karnataka, India', description: 'Basavana Bagewadi, Karnataka, India', lat: 16.5800, lng: 75.9700, type: 'taluk' },
  { name: 'Ranebennur', secondary: 'Haveri, Karnataka, India', description: 'Ranebennur, Karnataka, India', lat: 14.6200, lng: 75.6200, type: 'taluk' },
  { name: 'Byadgi', secondary: 'Haveri, Karnataka, India', description: 'Byadgi, Karnataka, India', lat: 14.6800, lng: 75.4900, type: 'taluk' },
  { name: 'Hirekerur', secondary: 'Haveri, Karnataka, India', description: 'Hirekerur, Karnataka, India', lat: 14.4600, lng: 75.3900, type: 'taluk' },
  { name: 'Hangal', secondary: 'Haveri, Karnataka, India', description: 'Hangal, Karnataka, India', lat: 14.7600, lng: 75.1300, type: 'taluk' },
  { name: 'Shiggaon', secondary: 'Haveri, Karnataka, India', description: 'Shiggaon, Karnataka, India', lat: 14.9900, lng: 75.2300, type: 'taluk' },
  { name: 'Savanur', secondary: 'Haveri, Karnataka, India', description: 'Savanur, Karnataka, India', lat: 14.9700, lng: 75.3400, type: 'taluk' },
  { name: 'Ron', secondary: 'Gadag, Karnataka, India', description: 'Ron, Karnataka, India', lat: 15.7000, lng: 75.7300, type: 'taluk' },
  { name: 'Shirhatti', secondary: 'Gadag, Karnataka, India', description: 'Shirhatti, Karnataka, India', lat: 15.2300, lng: 75.5800, type: 'taluk' },
  { name: 'Nargund', secondary: 'Gadag, Karnataka, India', description: 'Nargund, Karnataka, India', lat: 15.7200, lng: 75.3900, type: 'taluk' },
  { name: 'Mundargi', secondary: 'Gadag, Karnataka, India', description: 'Mundargi, Karnataka, India', lat: 15.2100, lng: 75.8900, type: 'taluk' },
  { name: 'Kundgol', secondary: 'Dharwad, Karnataka, India', description: 'Kundgol, Karnataka, India', lat: 15.2500, lng: 75.2500, type: 'taluk' },
  { name: 'Navalgund', secondary: 'Dharwad, Karnataka, India', description: 'Navalgund, Karnataka, India', lat: 15.5600, lng: 75.3600, type: 'taluk' },
  { name: 'Kalghatgi', secondary: 'Dharwad, Karnataka, India', description: 'Kalghatgi, Karnataka, India', lat: 15.1800, lng: 74.9700, type: 'taluk' },
  { name: 'Bailhongal', secondary: 'Belagavi, Karnataka, India', description: 'Bailhongal, Karnataka, India', lat: 15.8200, lng: 74.8600, type: 'taluk' },
  { name: 'Saundatti', secondary: 'Belagavi, Karnataka, India', description: 'Saundatti, Karnataka, India', lat: 15.7700, lng: 75.1200, type: 'taluk' },
  { name: 'Ramdurg', secondary: 'Belagavi, Karnataka, India', description: 'Ramdurg, Karnataka, India', lat: 15.9500, lng: 75.3000, type: 'taluk' },
  { name: 'Athani', secondary: 'Belagavi, Karnataka, India', description: 'Athani, Karnataka, India', lat: 16.7300, lng: 75.0600, type: 'taluk' },
  { name: 'Raybag', secondary: 'Belagavi, Karnataka, India', description: 'Raybag, Karnataka, India', lat: 16.4900, lng: 74.7800, type: 'taluk' },
  { name: 'Hukkeri', secondary: 'Belagavi, Karnataka, India', description: 'Hukkeri, Karnataka, India', lat: 16.2300, lng: 74.6000, type: 'taluk' },
  { name: 'Khanapur', secondary: 'Belagavi, Karnataka, India', description: 'Khanapur, Karnataka, India', lat: 15.6300, lng: 74.5200, type: 'taluk' },
  { name: 'Nipani', secondary: 'Belagavi, Karnataka, India', description: 'Nipani, Karnataka, India', lat: 16.4000, lng: 74.3800, type: 'town' },

  // --- TELANGANA DISTRICTS & CITIES ---
  { name: 'Karimnagar', secondary: 'District, Telangana, India', description: 'Karimnagar, Telangana, India', lat: 18.4386, lng: 79.1288, type: 'district' },
  { name: 'Hyderabad', secondary: 'District, Telangana, India', description: 'Hyderabad, Telangana, India', lat: 17.3850, lng: 78.4867, type: 'city' },
  { name: 'Warangal', secondary: 'District, Telangana, India', description: 'Warangal, Telangana, India', lat: 17.9689, lng: 79.5941, type: 'district' },
  { name: 'Hanamkonda', secondary: 'District, Telangana, India', description: 'Hanamkonda, Telangana, India', lat: 18.0138, lng: 79.5444, type: 'district' },
  { name: 'Nizamabad', secondary: 'District, Telangana, India', description: 'Nizamabad, Telangana, India', lat: 18.6725, lng: 78.0941, type: 'district' },
  { name: 'Khammam', secondary: 'District, Telangana, India', description: 'Khammam, Telangana, India', lat: 17.2473, lng: 80.1514, type: 'district' },
  { name: 'Nalgonda', secondary: 'District, Telangana, India', description: 'Nalgonda, Telangana, India', lat: 17.0577, lng: 79.2684, type: 'district' },
  { name: 'Mahabubnagar', secondary: 'District, Telangana, India', description: 'Mahabubnagar, Telangana, India', lat: 16.7488, lng: 77.9856, type: 'district' },
  { name: 'Ranga Reddy', secondary: 'District, Telangana, India', description: 'Ranga Reddy, Telangana, India', lat: 17.3000, lng: 78.4000, type: 'district' },
  { name: 'Medchal-Malkajgiri', secondary: 'District, Telangana, India', description: 'Medchal-Malkajgiri, Telangana, India', lat: 17.6297, lng: 78.4814, type: 'district' },
  { name: 'Sangareddy', secondary: 'District, Telangana, India', description: 'Sangareddy, Telangana, India', lat: 17.6193, lng: 78.0811, type: 'district' },
  { name: 'Siddipet', secondary: 'District, Telangana, India', description: 'Siddipet, Telangana, India', lat: 18.1018, lng: 78.8520, type: 'district' },
  { name: 'Adilabad', secondary: 'District, Telangana, India', description: 'Adilabad, Telangana, India', lat: 19.6641, lng: 78.5320, type: 'district' },
  { name: 'Mancherial', secondary: 'District, Telangana, India', description: 'Mancherial, Telangana, India', lat: 18.8679, lng: 79.4639, type: 'district' },
  { name: 'Nirmal', secondary: 'District, Telangana, India', description: 'Nirmal, Telangana, India', lat: 19.0964, lng: 78.3429, type: 'district' },
  { name: 'Jagtial', secondary: 'District, Telangana, India', description: 'Jagtial, Telangana, India', lat: 18.7946, lng: 78.9127, type: 'district' },
  { name: 'Peddapalli', secondary: 'District, Telangana, India', description: 'Peddapalli, Telangana, India', lat: 18.6148, lng: 79.3807, type: 'district' },
  { name: 'Rajanna Sircilla', secondary: 'District, Telangana, India', description: 'Rajanna Sircilla, Telangana, India', lat: 18.3847, lng: 78.8340, type: 'district' },
  { name: 'Kamareddy', secondary: 'District, Telangana, India', description: 'Kamareddy, Telangana, India', lat: 18.3228, lng: 78.3414, type: 'district' },
  { name: 'Vikarabad', secondary: 'District, Telangana, India', description: 'Vikarabad, Telangana, India', lat: 17.3364, lng: 77.9048, type: 'district' },
  { name: 'Suryapet', secondary: 'District, Telangana, India', description: 'Suryapet, Telangana, India', lat: 17.1439, lng: 79.6239, type: 'district' },
  { name: 'Yadadri Bhuvanagiri', secondary: 'District, Telangana, India', description: 'Yadadri Bhuvanagiri, Telangana, India', lat: 17.5100, lng: 78.8900, type: 'district' },
  { name: 'Bhadradri Kothagudem', secondary: 'District, Telangana, India', description: 'Bhadradri Kothagudem, Telangana, India', lat: 17.5500, lng: 80.6200, type: 'district' },
  { name: 'Mahabubabad', secondary: 'District, Telangana, India', description: 'Mahabubabad, Telangana, India', lat: 17.5986, lng: 80.0039, type: 'district' },
  { name: 'Jangaon', secondary: 'District, Telangana, India', description: 'Jangaon, Telangana, India', lat: 17.7239, lng: 79.1624, type: 'district' },
  { name: 'Jayashankar Bhupalpally', secondary: 'District, Telangana, India', description: 'Jayashankar Bhupalpally, Telangana, India', lat: 18.4300, lng: 79.8600, type: 'district' },
  { name: 'Mulugu', secondary: 'District, Telangana, India', description: 'Mulugu, Telangana, India', lat: 18.1900, lng: 79.9400, type: 'district' },
  { name: 'Nagarkurnool', secondary: 'District, Telangana, India', description: 'Nagarkurnool, Telangana, India', lat: 16.4800, lng: 78.3300, type: 'district' },
  { name: 'Wanaparthy', secondary: 'District, Telangana, India', description: 'Wanaparthy, Telangana, India', lat: 16.3600, lng: 78.0600, type: 'district' },
  { name: 'Jogulamba Gadwal', secondary: 'District, Telangana, India', description: 'Jogulamba Gadwal, Telangana, India', lat: 16.2300, lng: 77.8000, type: 'district' },
  { name: 'Narayanpet', secondary: 'District, Telangana, India', description: 'Narayanpet, Telangana, India', lat: 16.7300, lng: 77.5000, type: 'district' },
  { name: 'Kumuram Bheem Asifabad', secondary: 'District, Telangana, India', description: 'Kumuram Bheem Asifabad, Telangana, India', lat: 19.3600, lng: 79.2800, type: 'district' },
  { name: 'Medak', secondary: 'District, Telangana, India', description: 'Medak, Telangana, India', lat: 18.0469, lng: 78.2614, type: 'district' },

  // --- ANDHRA PRADESH DISTRICTS & CITIES ---
  { name: 'Visakhapatnam', secondary: 'District, Andhra Pradesh, India', description: 'Visakhapatnam, Andhra Pradesh, India', lat: 17.6868, lng: 83.2185, type: 'city' },
  { name: 'Vijayawada', secondary: 'NTR District, Andhra Pradesh, India', description: 'Vijayawada, Andhra Pradesh, India', lat: 16.5062, lng: 80.6480, type: 'city' },
  { name: 'Guntur', secondary: 'District, Andhra Pradesh, India', description: 'Guntur, Andhra Pradesh, India', lat: 16.3067, lng: 80.4365, type: 'district' },
  { name: 'Tirupati', secondary: 'District, Andhra Pradesh, India', description: 'Tirupati, Andhra Pradesh, India', lat: 13.6288, lng: 79.4192, type: 'district' },
  { name: 'Kurnool', secondary: 'District, Andhra Pradesh, India', description: 'Kurnool, Andhra Pradesh, India', lat: 15.8281, lng: 78.0373, type: 'district' },
  { name: 'Nellore', secondary: 'SPSR Nellore District, Andhra Pradesh, India', description: 'Nellore, Andhra Pradesh, India', lat: 14.4426, lng: 79.9865, type: 'district' },
  { name: 'Kadapa', secondary: 'YSR District, Andhra Pradesh, India', description: 'Kadapa, Andhra Pradesh, India', lat: 14.4673, lng: 78.8242, type: 'district' },
  { name: 'Kakinada', secondary: 'District, Andhra Pradesh, India', description: 'Kakinada, Andhra Pradesh, India', lat: 16.9891, lng: 82.2475, type: 'district' },
  { name: 'Rajahmundry', secondary: 'East Godavari, Andhra Pradesh, India', description: 'Rajahmundry, Andhra Pradesh, India', lat: 17.0005, lng: 81.8040, type: 'city' },
  { name: 'Ananthapuramu', secondary: 'District, Andhra Pradesh, India', description: 'Ananthapuramu, Andhra Pradesh, India', lat: 14.6819, lng: 77.6006, type: 'district' },
  { name: 'Chittoor', secondary: 'District, Andhra Pradesh, India', description: 'Chittoor, Andhra Pradesh, India', lat: 13.2172, lng: 79.1003, type: 'district' },
  { name: 'Eluru', secondary: 'District, Andhra Pradesh, India', description: 'Eluru, Andhra Pradesh, India', lat: 16.7107, lng: 81.0952, type: 'district' },
  { name: 'Ongole', secondary: 'Prakasam District, Andhra Pradesh, India', description: 'Ongole, Andhra Pradesh, India', lat: 15.5057, lng: 80.0499, type: 'district' },
  { name: 'Srikakulam', secondary: 'District, Andhra Pradesh, India', description: 'Srikakulam, Andhra Pradesh, India', lat: 18.2969, lng: 83.8968, type: 'district' },
  { name: 'Vizianagaram', secondary: 'District, Andhra Pradesh, India', description: 'Vizianagaram, Andhra Pradesh, India', lat: 18.1133, lng: 83.3977, type: 'district' },
  { name: 'Nandyal', secondary: 'District, Andhra Pradesh, India', description: 'Nandyal, Andhra Pradesh, India', lat: 15.4886, lng: 78.4836, type: 'district' },
  { name: 'Machilipatnam', secondary: 'Krishna District, Andhra Pradesh, India', description: 'Machilipatnam, Andhra Pradesh, India', lat: 16.1875, lng: 81.1389, type: 'district' },
  { name: 'Bhimavaram', secondary: 'West Godavari, Andhra Pradesh, India', description: 'Bhimavaram, Andhra Pradesh, India', lat: 16.5449, lng: 81.5212, type: 'district' },
  { name: 'Anakapalli', secondary: 'District, Andhra Pradesh, India', description: 'Anakapalli, Andhra Pradesh, India', lat: 17.6913, lng: 83.0039, type: 'district' },
  { name: 'Narasaraopet', secondary: 'Palnadu District, Andhra Pradesh, India', description: 'Narasaraopet, Andhra Pradesh, India', lat: 16.2360, lng: 80.0499, type: 'district' },
  { name: 'Bapatla', secondary: 'District, Andhra Pradesh, India', description: 'Bapatla, Andhra Pradesh, India', lat: 15.9042, lng: 80.4676, type: 'district' },
  { name: 'Rayachoti', secondary: 'Annamayya District, Andhra Pradesh, India', description: 'Rayachoti, Andhra Pradesh, India', lat: 14.0573, lng: 78.7523, type: 'district' },
  { name: 'Puttaparthi', secondary: 'Sri Sathya Sai District, Andhra Pradesh, India', description: 'Puttaparthi, Andhra Pradesh, India', lat: 14.1687, lng: 77.8109, type: 'district' },

  // --- MAHARASHTRA DISTRICTS, TALUKS & CITIES ---
  { name: 'Mumbai', secondary: 'Maharashtra, India', description: 'Mumbai, Maharashtra, India', lat: 19.0760, lng: 72.8777, type: 'city' },
  { name: 'Pune', secondary: 'District, Maharashtra, India', description: 'Pune, Maharashtra, India', lat: 18.5204, lng: 73.8567, type: 'city' },
  { name: 'Nagpur', secondary: 'District, Maharashtra, India', description: 'Nagpur, Maharashtra, India', lat: 21.1458, lng: 79.0882, type: 'city' },
  { name: 'Thane', secondary: 'District, Maharashtra, India', description: 'Thane, Maharashtra, India', lat: 19.2183, lng: 72.9781, type: 'district' },
  { name: 'Nashik', secondary: 'District, Maharashtra, India', description: 'Nashik, Maharashtra, India', lat: 19.9975, lng: 73.7898, type: 'district' },
  { name: 'Chhatrapati Sambhajinagar', secondary: 'Aurangabad, Maharashtra, India', description: 'Chhatrapati Sambhajinagar, Maharashtra, India', lat: 19.8762, lng: 75.3433, type: 'district' },
  { name: 'Aurangabad', secondary: 'Chhatrapati Sambhajinagar, Maharashtra, India', description: 'Aurangabad, Maharashtra, India', lat: 19.8762, lng: 75.3433, type: 'district' },
  { name: 'Solapur', secondary: 'District, Maharashtra, India', description: 'Solapur, Maharashtra, India', lat: 17.6599, lng: 75.9064, type: 'district' },
  { name: 'Kolhapur', secondary: 'District, Maharashtra, India', description: 'Kolhapur, Maharashtra, India', lat: 16.7050, lng: 74.2433, type: 'district' },
  { name: 'Amravati', secondary: 'District, Maharashtra, India', description: 'Amravati, Maharashtra, India', lat: 20.9320, lng: 77.7523, type: 'district' },
  { name: 'Nanded', secondary: 'District, Maharashtra, India', description: 'Nanded, Maharashtra, India', lat: 19.1383, lng: 77.3210, type: 'district' },
  { name: 'Sangli', secondary: 'District, Maharashtra, India', description: 'Sangli, Maharashtra, India', lat: 16.8524, lng: 74.5815, type: 'district' },
  { name: 'Jalgaon', secondary: 'District, Maharashtra, India', description: 'Jalgaon, Maharashtra, India', lat: 21.0077, lng: 75.5626, type: 'district' },
  { name: 'Akola', secondary: 'District, Maharashtra, India', description: 'Akola, Maharashtra, India', lat: 20.7002, lng: 77.0082, type: 'district' },
  { name: 'Latur', secondary: 'District, Maharashtra, India', description: 'Latur, Maharashtra, India', lat: 18.4088, lng: 76.5604, type: 'district' },
  { name: 'Dhule', secondary: 'District, Maharashtra, India', description: 'Dhule, Maharashtra, India', lat: 20.9042, lng: 74.7749, type: 'district' },
  { name: 'Ahmednagar', secondary: 'Ahilyanagar, Maharashtra, India', description: 'Ahmednagar, Maharashtra, India', lat: 19.0952, lng: 74.7496, type: 'district' },
  { name: 'Ahilyanagar', secondary: 'Ahmednagar District, Maharashtra, India', description: 'Ahilyanagar, Maharashtra, India', lat: 19.0952, lng: 74.7496, type: 'district' },
  { name: 'Chandrapur', secondary: 'District, Maharashtra, India', description: 'Chandrapur, Maharashtra, India', lat: 19.9615, lng: 79.2961, type: 'district' },
  { name: 'Parbhani', secondary: 'District, Maharashtra, India', description: 'Parbhani, Maharashtra, India', lat: 19.2644, lng: 76.7767, type: 'district' },
  { name: 'Jalna', secondary: 'District, Maharashtra, India', description: 'Jalna, Maharashtra, India', lat: 19.8347, lng: 75.8816, type: 'district' },
  { name: 'Beed', secondary: 'District, Maharashtra, India', description: 'Beed, Maharashtra, India', lat: 18.9891, lng: 75.7601, type: 'district' },
  { name: 'Yavatmal', secondary: 'District, Maharashtra, India', description: 'Yavatmal, Maharashtra, India', lat: 20.3888, lng: 78.1204, type: 'district' },
  { name: 'Satara', secondary: 'District, Maharashtra, India', description: 'Satara, Maharashtra, India', lat: 17.6805, lng: 74.0183, type: 'district' },
  { name: 'Buldhana', secondary: 'District, Maharashtra, India', description: 'Buldhana, Maharashtra, India', lat: 20.5292, lng: 76.1843, type: 'district' },
  { name: 'Wardha', secondary: 'District, Maharashtra, India', description: 'Wardha, Maharashtra, India', lat: 20.7453, lng: 78.6022, type: 'district' },
  { name: 'Dharashiv', secondary: 'Osmanabad, Maharashtra, India', description: 'Dharashiv, Maharashtra, India', lat: 18.1856, lng: 76.0419, type: 'district' },
  { name: 'Osmanabad', secondary: 'Dharashiv, Maharashtra, India', description: 'Osmanabad, Maharashtra, India', lat: 18.1856, lng: 76.0419, type: 'district' },
  { name: 'Gondia', secondary: 'District, Maharashtra, India', description: 'Gondia, Maharashtra, India', lat: 21.4598, lng: 80.1961, type: 'district' },
  { name: 'Bhandara', secondary: 'District, Maharashtra, India', description: 'Bhandara, Maharashtra, India', lat: 21.1667, lng: 79.6500, type: 'district' },
  { name: 'Washim', secondary: 'District, Maharashtra, India', description: 'Washim, Maharashtra, India', lat: 20.1110, lng: 77.1340, type: 'district' },
  { name: 'Hingoli', secondary: 'District, Maharashtra, India', description: 'Hingoli, Maharashtra, India', lat: 19.7180, lng: 77.1477, type: 'district' },
  { name: 'Gadchiroli', secondary: 'District, Maharashtra, India', description: 'Gadchiroli, Maharashtra, India', lat: 20.1804, lng: 80.0039, type: 'district' },
  { name: 'Palghar', secondary: 'District, Maharashtra, India', description: 'Palghar, Maharashtra, India', lat: 19.6967, lng: 72.7699, type: 'district' },
  { name: 'Raigad', secondary: 'District, Maharashtra, India', description: 'Raigad, Maharashtra, India', lat: 18.5158, lng: 73.1822, type: 'district' },
  { name: 'Ratnagiri', secondary: 'District, Maharashtra, India', description: 'Ratnagiri, Maharashtra, India', lat: 16.9902, lng: 73.3120, type: 'district' },
  { name: 'Sindhudurg', secondary: 'District, Maharashtra, India', description: 'Sindhudurg, Maharashtra, India', lat: 16.1219, lng: 73.7144, type: 'district' },
  { name: 'Nandurbar', secondary: 'District, Maharashtra, India', description: 'Nandurbar, Maharashtra, India', lat: 21.3698, lng: 74.2393, type: 'district' },
  { name: 'Hiware Bazar', secondary: 'Ahilyanagar, Maharashtra, India', description: 'Hiware Bazar, Maharashtra, India', lat: 19.0680, lng: 74.6012, type: 'village' },
  { name: 'Shirdi', secondary: 'Rahata, Ahilyanagar, Maharashtra, India', description: 'Shirdi, Maharashtra, India', lat: 19.7645, lng: 74.4762, type: 'town' },

  // --- TAMIL NADU DISTRICTS & CITIES ---
  { name: 'Chennai', secondary: 'District, Tamil Nadu, India', description: 'Chennai, Tamil Nadu, India', lat: 13.0827, lng: 80.2707, type: 'city' },
  { name: 'Coimbatore', secondary: 'District, Tamil Nadu, India', description: 'Coimbatore, Tamil Nadu, India', lat: 11.0168, lng: 76.9558, type: 'city' },
  { name: 'Madurai', secondary: 'District, Tamil Nadu, India', description: 'Madurai, Tamil Nadu, India', lat: 9.9252, lng: 78.1198, type: 'city' },
  { name: 'Tiruchirappalli', secondary: 'District, Tamil Nadu, India', description: 'Tiruchirappalli, Tamil Nadu, India', lat: 10.7905, lng: 78.7047, type: 'district' },
  { name: 'Trichy', secondary: 'Tiruchirappalli, Tamil Nadu, India', description: 'Trichy, Tamil Nadu, India', lat: 10.7905, lng: 78.7047, type: 'district' },
  { name: 'Salem', secondary: 'District, Tamil Nadu, India', description: 'Salem, Tamil Nadu, India', lat: 11.6643, lng: 78.1460, type: 'district' },
  { name: 'Tirunelveli', secondary: 'District, Tamil Nadu, India', description: 'Tirunelveli, Tamil Nadu, India', lat: 8.7139, lng: 77.7567, type: 'district' },
  { name: 'Tiruppur', secondary: 'District, Tamil Nadu, India', description: 'Tiruppur, Tamil Nadu, India', lat: 11.1085, lng: 77.3411, type: 'district' },
  { name: 'Erode', secondary: 'District, Tamil Nadu, India', description: 'Erode, Tamil Nadu, India', lat: 11.3410, lng: 77.7172, type: 'district' },
  { name: 'Vellore', secondary: 'District, Tamil Nadu, India', description: 'Vellore, Tamil Nadu, India', lat: 12.9165, lng: 79.1325, type: 'district' },
  { name: 'Thoothukudi', secondary: 'District, Tamil Nadu, India', description: 'Thoothukudi, Tamil Nadu, India', lat: 8.7642, lng: 78.1348, type: 'district' },
  { name: 'Dindigul', secondary: 'District, Tamil Nadu, India', description: 'Dindigul, Tamil Nadu, India', lat: 10.3673, lng: 77.9803, type: 'district' },
  { name: 'Thanjavur', secondary: 'District, Tamil Nadu, India', description: 'Thanjavur, Tamil Nadu, India', lat: 10.7870, lng: 79.1378, type: 'district' },
  { name: 'Ranipet', secondary: 'District, Tamil Nadu, India', description: 'Ranipet, Tamil Nadu, India', lat: 12.9272, lng: 79.3330, type: 'district' },
  { name: 'Virudhunagar', secondary: 'District, Tamil Nadu, India', description: 'Virudhunagar, Tamil Nadu, India', lat: 9.5680, lng: 77.9624, type: 'district' },
  { name: 'Karur', secondary: 'District, Tamil Nadu, India', description: 'Karur, Tamil Nadu, India', lat: 10.9601, lng: 78.0766, type: 'district' },
  { name: 'Karaikudi', secondary: 'Sivaganga, Tamil Nadu, India', description: 'Karaikudi, Tamil Nadu, India', lat: 10.0735, lng: 78.7732, type: 'town' },
  { name: 'Sivaganga', secondary: 'District, Tamil Nadu, India', description: 'Sivaganga, Tamil Nadu, India', lat: 9.8433, lng: 78.4809, type: 'district' },
  { name: 'Nilgiris', secondary: 'District, Tamil Nadu, India', description: 'Nilgiris, Tamil Nadu, India', lat: 11.4167, lng: 76.7000, type: 'district' },
  { name: 'Ooty', secondary: 'Nilgiris, Tamil Nadu, India', description: 'Ooty, Tamil Nadu, India', lat: 11.4102, lng: 76.6950, type: 'town' },
  { name: 'Krishnagiri', secondary: 'District, Tamil Nadu, India', description: 'Krishnagiri, Tamil Nadu, India', lat: 12.5186, lng: 78.2137, type: 'district' },
  { name: 'Hosur', secondary: 'Krishnagiri, Tamil Nadu, India', description: 'Hosur, Tamil Nadu, India', lat: 12.7409, lng: 77.8253, type: 'city' },
  { name: 'Kanyakumari', secondary: 'District, Tamil Nadu, India', description: 'Kanyakumari, Tamil Nadu, India', lat: 8.0883, lng: 77.5385, type: 'district' },
  { name: 'Kanchipuram', secondary: 'District, Tamil Nadu, India', description: 'Kanchipuram, Tamil Nadu, India', lat: 12.8342, lng: 79.7036, type: 'district' },
  { name: 'Namakkal', secondary: 'District, Tamil Nadu, India', description: 'Namakkal, Tamil Nadu, India', lat: 11.2189, lng: 78.1674, type: 'district' },
  { name: 'Cuddalore', secondary: 'District, Tamil Nadu, India', description: 'Cuddalore, Tamil Nadu, India', lat: 11.7480, lng: 79.7714, type: 'district' },
  { name: 'Tiruvallur', secondary: 'District, Tamil Nadu, India', description: 'Tiruvallur, Tamil Nadu, India', lat: 13.1432, lng: 79.9083, type: 'district' },
  { name: 'Tiruvannamalai', secondary: 'District, Tamil Nadu, India', description: 'Tiruvannamalai, Tamil Nadu, India', lat: 12.2253, lng: 79.0747, type: 'district' },
  { name: 'Nagapattinam', secondary: 'District, Tamil Nadu, India', description: 'Nagapattinam, Tamil Nadu, India', lat: 10.7672, lng: 79.8449, type: 'district' },
  { name: 'Viluppuram', secondary: 'District, Tamil Nadu, India', description: 'Viluppuram, Tamil Nadu, India', lat: 11.9401, lng: 79.4861, type: 'district' },
  { name: 'Ramanathapuram', secondary: 'District, Tamil Nadu, India', description: 'Ramanathapuram, Tamil Nadu, India', lat: 9.3639, lng: 78.8395, type: 'district' },
  { name: 'Perambalur', secondary: 'District, Tamil Nadu, India', description: 'Perambalur, Tamil Nadu, India', lat: 11.2342, lng: 78.8820, type: 'district' },
  { name: 'Pudukkottai', secondary: 'District, Tamil Nadu, India', description: 'Pudukkottai, Tamil Nadu, India', lat: 10.3797, lng: 78.8208, type: 'district' },
  { name: 'Theni', secondary: 'District, Tamil Nadu, India', description: 'Theni, Tamil Nadu, India', lat: 10.0104, lng: 77.4768, type: 'district' },
  { name: 'Dharmapuri', secondary: 'District, Tamil Nadu, India', description: 'Dharmapuri, Tamil Nadu, India', lat: 12.1211, lng: 78.1582, type: 'district' },
  { name: 'Tiruvarur', secondary: 'District, Tamil Nadu, India', description: 'Tiruvarur, Tamil Nadu, India', lat: 10.7715, lng: 79.6368, type: 'district' },
  { name: 'Tenkasi', secondary: 'District, Tamil Nadu, India', description: 'Tenkasi, Tamil Nadu, India', lat: 8.9594, lng: 77.3152, type: 'district' },
  { name: 'Chengalpattu', secondary: 'District, Tamil Nadu, India', description: 'Chengalpattu, Tamil Nadu, India', lat: 12.6819, lng: 79.9888, type: 'district' },
  { name: 'Kallakurichi', secondary: 'District, Tamil Nadu, India', description: 'Kallakurichi, Tamil Nadu, India', lat: 11.7383, lng: 78.9639, type: 'district' },
  { name: 'Mayiladuthurai', secondary: 'District, Tamil Nadu, India', description: 'Mayiladuthurai, Tamil Nadu, India', lat: 11.1075, lng: 79.6524, type: 'district' },
  { name: 'Tirupathur', secondary: 'District, Tamil Nadu, India', description: 'Tirupathur, Tamil Nadu, India', lat: 12.4925, lng: 78.5678, type: 'district' },
  { name: 'Ariyalur', secondary: 'District, Tamil Nadu, India', description: 'Ariyalur, Tamil Nadu, India', lat: 11.1401, lng: 79.0786, type: 'district' },

  // --- KERALA DISTRICTS & CITIES ---
  { name: 'Thiruvananthapuram', secondary: 'District, Kerala, India', description: 'Thiruvananthapuram, Kerala, India', lat: 8.5241, lng: 76.9366, type: 'city' },
  { name: 'Kochi', secondary: 'Ernakulam, Kerala, India', description: 'Kochi, Kerala, India', lat: 9.9312, lng: 76.2673, type: 'city' },
  { name: 'Ernakulam', secondary: 'District, Kerala, India', description: 'Ernakulam, Kerala, India', lat: 9.9816, lng: 76.2999, type: 'district' },
  { name: 'Kozhikode', secondary: 'District, Kerala, India', description: 'Kozhikode, Kerala, India', lat: 11.2588, lng: 75.7804, type: 'district' },
  { name: 'Calicut', secondary: 'Kozhikode, Kerala, India', description: 'Calicut, Kerala, India', lat: 11.2588, lng: 75.7804, type: 'city' },
  { name: 'Thrissur', secondary: 'District, Kerala, India', description: 'Thrissur, Kerala, India', lat: 10.5276, lng: 76.2144, type: 'district' },
  { name: 'Kollam', secondary: 'District, Kerala, India', description: 'Kollam, Kerala, India', lat: 8.8932, lng: 76.6141, type: 'district' },
  { name: 'Palakkad', secondary: 'District, Kerala, India', description: 'Palakkad, Kerala, India', lat: 10.7867, lng: 76.6548, type: 'district' },
  { name: 'Malappuram', secondary: 'District, Kerala, India', description: 'Malappuram, Kerala, India', lat: 11.0510, lng: 76.0711, type: 'district' },
  { name: 'Kannur', secondary: 'District, Kerala, India', description: 'Kannur, Kerala, India', lat: 11.8745, lng: 75.3704, type: 'district' },
  { name: 'Alappuzha', secondary: 'District, Kerala, India', description: 'Alappuzha, Kerala, India', lat: 9.4981, lng: 76.3388, type: 'district' },
  { name: 'Kottayam', secondary: 'District, Kerala, India', description: 'Kottayam, Kerala, India', lat: 9.5916, lng: 76.5222, type: 'district' },
  { name: 'Kasaragod', secondary: 'District, Kerala, India', description: 'Kasaragod, Kerala, India', lat: 12.4996, lng: 74.9869, type: 'district' },
  { name: 'Pathanamthitta', secondary: 'District, Kerala, India', description: 'Pathanamthitta, Kerala, India', lat: 9.2648, lng: 76.7870, type: 'district' },
  { name: 'Idukki', secondary: 'District, Kerala, India', description: 'Idukki, Kerala, India', lat: 9.8500, lng: 76.9700, type: 'district' },
  { name: 'Wayanad', secondary: 'District, Kerala, India', description: 'Wayanad, Kerala, India', lat: 11.6854, lng: 76.1320, type: 'district' },

  // --- UTTAR PRADESH DISTRICTS & CITIES ---
  { name: 'Lucknow', secondary: 'District, Uttar Pradesh, India', description: 'Lucknow, Uttar Pradesh, India', lat: 26.8467, lng: 80.9462, type: 'city' },
  { name: 'Kanpur', secondary: 'District, Uttar Pradesh, India', description: 'Kanpur, Uttar Pradesh, India', lat: 26.4499, lng: 80.3319, type: 'city' },
  { name: 'Varanasi', secondary: 'District, Uttar Pradesh, India', description: 'Varanasi, Uttar Pradesh, India', lat: 25.3176, lng: 82.9739, type: 'city' },
  { name: 'Prayagraj', secondary: 'District, Uttar Pradesh, India', description: 'Prayagraj, Uttar Pradesh, India', lat: 25.4358, lng: 81.8463, type: 'city' },
  { name: 'Allahabad', secondary: 'Prayagraj, Uttar Pradesh, India', description: 'Allahabad, Uttar Pradesh, India', lat: 25.4358, lng: 81.8463, type: 'city' },
  { name: 'Agra', secondary: 'District, Uttar Pradesh, India', description: 'Agra, Uttar Pradesh, India', lat: 27.1767, lng: 78.0081, type: 'city' },
  { name: 'Noida', secondary: 'Gautam Buddha Nagar, Uttar Pradesh, India', description: 'Noida, Uttar Pradesh, India', lat: 28.5355, lng: 77.3910, type: 'city' },
  { name: 'Greater Noida', secondary: 'Gautam Buddha Nagar, Uttar Pradesh, India', description: 'Greater Noida, Uttar Pradesh, India', lat: 28.4744, lng: 77.5040, type: 'city' },
  { name: 'Ghaziabad', secondary: 'District, Uttar Pradesh, India', description: 'Ghaziabad, Uttar Pradesh, India', lat: 28.6692, lng: 77.4538, type: 'city' },
  { name: 'Meerut', secondary: 'District, Uttar Pradesh, India', description: 'Meerut, Uttar Pradesh, India', lat: 28.9845, lng: 77.7064, type: 'district' },
  { name: 'Bareilly', secondary: 'District, Uttar Pradesh, India', description: 'Bareilly, Uttar Pradesh, India', lat: 28.3670, lng: 79.4304, type: 'district' },
  { name: 'Aligarh', secondary: 'District, Uttar Pradesh, India', description: 'Aligarh, Uttar Pradesh, India', lat: 27.8974, lng: 78.0880, type: 'district' },
  { name: 'Moradabad', secondary: 'District, Uttar Pradesh, India', description: 'Moradabad, Uttar Pradesh, India', lat: 28.8351, lng: 78.7752, type: 'district' },
  { name: 'Saharanpur', secondary: 'District, Uttar Pradesh, India', description: 'Saharanpur, Uttar Pradesh, India', lat: 29.9642, lng: 77.5460, type: 'district' },
  { name: 'Gorakhpur', secondary: 'District, Uttar Pradesh, India', description: 'Gorakhpur, Uttar Pradesh, India', lat: 26.7606, lng: 83.3732, type: 'district' },
  { name: 'Ayodhya', secondary: 'District, Uttar Pradesh, India', description: 'Ayodhya, Uttar Pradesh, India', lat: 26.7922, lng: 82.1998, type: 'district' },
  { name: 'Faizabad', secondary: 'Ayodhya, Uttar Pradesh, India', description: 'Faizabad, Uttar Pradesh, India', lat: 26.7730, lng: 82.1460, type: 'city' },
  { name: 'Jhansi', secondary: 'District, Uttar Pradesh, India', description: 'Jhansi, Uttar Pradesh, India', lat: 25.4484, lng: 78.5685, type: 'district' },
  { name: 'Muzaffarnagar', secondary: 'District, Uttar Pradesh, India', description: 'Muzaffarnagar, Uttar Pradesh, India', lat: 29.4727, lng: 77.7085, type: 'district' },
  { name: 'Mathura', secondary: 'District, Uttar Pradesh, India', description: 'Mathura, Uttar Pradesh, India', lat: 27.4924, lng: 77.6737, type: 'district' },
  { name: 'Firozabad', secondary: 'District, Uttar Pradesh, India', description: 'Firozabad, Uttar Pradesh, India', lat: 27.1591, lng: 78.3957, type: 'district' },
  { name: 'Malihabad', secondary: 'Lucknow, Uttar Pradesh, India', description: 'Malihabad, Uttar Pradesh, India', lat: 26.9906, lng: 80.6665, type: 'taluk' },

  // --- HARYANA & PUNJAB DISTRICTS & CITIES ---
  { name: 'Gurugram', secondary: 'District, Haryana, India', description: 'Gurugram, Haryana, India', lat: 28.4595, lng: 77.0266, type: 'city' },
  { name: 'Gurgaon', secondary: 'Gurugram, Haryana, India', description: 'Gurgaon, Haryana, India', lat: 28.4595, lng: 77.0266, type: 'city' },
  { name: 'Faridabad', secondary: 'District, Haryana, India', description: 'Faridabad, Haryana, India', lat: 28.4089, lng: 77.3178, type: 'city' },
  { name: 'Panipat', secondary: 'District, Haryana, India', description: 'Panipat, Haryana, India', lat: 29.3909, lng: 76.9635, type: 'district' },
  { name: 'Ambala', secondary: 'District, Haryana, India', description: 'Ambala, Haryana, India', lat: 30.3782, lng: 76.7767, type: 'district' },
  { name: 'Karnal', secondary: 'District, Haryana, India', description: 'Karnal, Haryana, India', lat: 29.6857, lng: 76.9905, type: 'district' },
  { name: 'Hisar', secondary: 'District, Haryana, India', description: 'Hisar, Haryana, India', lat: 29.1492, lng: 75.7217, type: 'district' },
  { name: 'Rohtak', secondary: 'District, Haryana, India', description: 'Rohtak, Haryana, India', lat: 28.8955, lng: 76.6066, type: 'district' },
  { name: 'Sonipat', secondary: 'District, Haryana, India', description: 'Sonipat, Haryana, India', lat: 28.9931, lng: 77.0151, type: 'district' },
  { name: 'Panchkula', secondary: 'District, Haryana, India', description: 'Panchkula, Haryana, India', lat: 30.6942, lng: 76.8606, type: 'district' },
  { name: 'Ludhiana', secondary: 'District, Punjab, India', description: 'Ludhiana, Punjab, India', lat: 30.9010, lng: 75.8573, type: 'city' },
  { name: 'Amritsar', secondary: 'District, Punjab, India', description: 'Amritsar, Punjab, India', lat: 31.6340, lng: 74.8723, type: 'city' },
  { name: 'Jalandhar', secondary: 'District, Punjab, India', description: 'Jalandhar, Punjab, India', lat: 31.3260, lng: 75.5762, type: 'district' },
  { name: 'Patiala', secondary: 'District, Punjab, India', description: 'Patiala, Punjab, India', lat: 30.3398, lng: 76.3869, type: 'district' },
  { name: 'Bathinda', secondary: 'District, Punjab, India', description: 'Bathinda, Punjab, India', lat: 30.2110, lng: 74.9455, type: 'district' },
  { name: 'Mohali', secondary: 'SAS Nagar, Punjab, India', description: 'Mohali, Punjab, India', lat: 30.7046, lng: 76.7179, type: 'city' },

  // --- RAJASTHAN DISTRICTS & CITIES ---
  { name: 'Jaipur', secondary: 'District, Rajasthan, India', description: 'Jaipur, Rajasthan, India', lat: 26.9124, lng: 75.7873, type: 'city' },
  { name: 'Jodhpur', secondary: 'District, Rajasthan, India', description: 'Jodhpur, Rajasthan, India', lat: 26.2389, lng: 73.0243, type: 'city' },
  { name: 'Udaipur', secondary: 'District, Rajasthan, India', description: 'Udaipur, Rajasthan, India', lat: 24.5854, lng: 73.7125, type: 'city' },
  { name: 'Kota', secondary: 'District, Rajasthan, India', description: 'Kota, Rajasthan, India', lat: 25.2138, lng: 75.8648, type: 'city' },
  { name: 'Bikaner', secondary: 'District, Rajasthan, India', description: 'Bikaner, Rajasthan, India', lat: 28.0229, lng: 73.3119, type: 'district' },
  { name: 'Ajmer', secondary: 'District, Rajasthan, India', description: 'Ajmer, Rajasthan, India', lat: 26.4499, lng: 74.6399, type: 'district' },
  { name: 'Alwar', secondary: 'District, Rajasthan, India', description: 'Alwar, Rajasthan, India', lat: 27.5530, lng: 76.6346, type: 'district' },
  { name: 'Bhilwara', secondary: 'District, Rajasthan, India', description: 'Bhilwara, Rajasthan, India', lat: 25.3216, lng: 74.6414, type: 'district' },
  { name: 'Sikar', secondary: 'District, Rajasthan, India', description: 'Sikar, Rajasthan, India', lat: 27.6094, lng: 75.1398, type: 'district' },
  { name: 'Bharatpur', secondary: 'District, Rajasthan, India', description: 'Bharatpur, Rajasthan, India', lat: 27.2152, lng: 77.5030, type: 'district' },
  { name: 'Pali', secondary: 'District, Rajasthan, India', description: 'Pali, Rajasthan, India', lat: 25.7711, lng: 73.3234, type: 'district' },
  { name: 'Sri Ganganagar', secondary: 'District, Rajasthan, India', description: 'Sri Ganganagar, Rajasthan, India', lat: 29.9038, lng: 73.8772, type: 'district' },
  { name: 'Barmer', secondary: 'District, Rajasthan, India', description: 'Barmer, Rajasthan, India', lat: 25.7521, lng: 71.3967, type: 'district' },
  { name: 'Jaisalmer', secondary: 'District, Rajasthan, India', description: 'Jaisalmer, Rajasthan, India', lat: 26.9157, lng: 70.9083, type: 'district' },

  // --- GUJARAT DISTRICTS & CITIES ---
  { name: 'Ahmedabad', secondary: 'District, Gujarat, India', description: 'Ahmedabad, Gujarat, India', lat: 23.0225, lng: 72.5714, type: 'city' },
  { name: 'Surat', secondary: 'District, Gujarat, India', description: 'Surat, Gujarat, India', lat: 21.1702, lng: 72.8311, type: 'city' },
  { name: 'Vadodara', secondary: 'District, Gujarat, India', description: 'Vadodara, Gujarat, India', lat: 22.3072, lng: 73.1812, type: 'city' },
  { name: 'Rajkot', secondary: 'District, Gujarat, India', description: 'Rajkot, Gujarat, India', lat: 22.3039, lng: 70.8022, type: 'city' },
  { name: 'Bhavnagar', secondary: 'District, Gujarat, India', description: 'Bhavnagar, Gujarat, India', lat: 21.7645, lng: 72.1519, type: 'district' },
  { name: 'Jamnagar', secondary: 'District, Gujarat, India', description: 'Jamnagar, Gujarat, India', lat: 22.4707, lng: 70.0577, type: 'district' },
  { name: 'Gandhinagar', secondary: 'District, Gujarat, India', description: 'Gandhinagar, Gujarat, India', lat: 23.2156, lng: 72.6369, type: 'city' },
  { name: 'Junagadh', secondary: 'District, Gujarat, India', description: 'Junagadh, Gujarat, India', lat: 21.5222, lng: 70.4579, type: 'district' },
  { name: 'Anand', secondary: 'District, Gujarat, India', description: 'Anand, Gujarat, India', lat: 22.5645, lng: 72.9289, type: 'district' },
  { name: 'Kutch', secondary: 'District, Gujarat, India', description: 'Kutch, Gujarat, India', lat: 23.7337, lng: 69.8597, type: 'district' },
  { name: 'Bhuj', secondary: 'Kutch, Gujarat, India', description: 'Bhuj, Gujarat, India', lat: 23.2420, lng: 69.6669, type: 'town' },
  { name: 'Mehsana', secondary: 'District, Gujarat, India', description: 'Mehsana, Gujarat, India', lat: 23.5880, lng: 72.3693, type: 'district' },
  { name: 'Morbi', secondary: 'District, Gujarat, India', description: 'Morbi, Gujarat, India', lat: 22.8173, lng: 70.8370, type: 'district' },
  { name: 'Bharuch', secondary: 'District, Gujarat, India', description: 'Bharuch, Gujarat, India', lat: 21.7051, lng: 72.9959, type: 'district' },
  { name: 'Valsad', secondary: 'District, Gujarat, India', description: 'Valsad, Gujarat, India', lat: 20.5992, lng: 72.9342, type: 'district' },
  { name: 'Navsari', secondary: 'District, Gujarat, India', description: 'Navsari, Gujarat, India', lat: 20.9500, lng: 72.9300, type: 'district' },
  { name: 'Patan', secondary: 'District, Gujarat, India', description: 'Patan, Gujarat, India', lat: 23.8500, lng: 72.1200, type: 'district' },
  { name: 'Punsari', secondary: 'Sabarkantha, Gujarat, India', description: 'Punsari, Gujarat, India', lat: 23.5134, lng: 73.0841, type: 'village' },

  // --- MADHYA PRADESH DISTRICTS & CITIES ---
  { name: 'Bhopal', secondary: 'District, Madhya Pradesh, India', description: 'Bhopal, Madhya Pradesh, India', lat: 23.2599, lng: 77.4126, type: 'city' },
  { name: 'Indore', secondary: 'District, Madhya Pradesh, India', description: 'Indore, Madhya Pradesh, India', lat: 22.7196, lng: 75.8577, type: 'city' },
  { name: 'Jabalpur', secondary: 'District, Madhya Pradesh, India', description: 'Jabalpur, Madhya Pradesh, India', lat: 23.1815, lng: 79.9864, type: 'city' },
  { name: 'Gwalior', secondary: 'District, Madhya Pradesh, India', description: 'Gwalior, Madhya Pradesh, India', lat: 26.2183, lng: 78.1828, type: 'city' },
  { name: 'Ujjain', secondary: 'District, Madhya Pradesh, India', description: 'Ujjain, Madhya Pradesh, India', lat: 23.1765, lng: 75.7885, type: 'city' },
  { name: 'Sagar', secondary: 'District, Madhya Pradesh, India', description: 'Sagar, Madhya Pradesh, India', lat: 23.8388, lng: 78.7378, type: 'district' },
  { name: 'Dewas', secondary: 'District, Madhya Pradesh, India', description: 'Dewas, Madhya Pradesh, India', lat: 22.9676, lng: 76.0534, type: 'district' },
  { name: 'Satna', secondary: 'District, Madhya Pradesh, India', description: 'Satna, Madhya Pradesh, India', lat: 24.6005, lng: 80.8322, type: 'district' },
  { name: 'Ratlam', secondary: 'District, Madhya Pradesh, India', description: 'Ratlam, Madhya Pradesh, India', lat: 23.3315, lng: 75.0367, type: 'district' },
  { name: 'Rewa', secondary: 'District, Madhya Pradesh, India', description: 'Rewa, Madhya Pradesh, India', lat: 24.5362, lng: 81.3037, type: 'district' },
  { name: 'Chhindwara', secondary: 'District, Madhya Pradesh, India', description: 'Chhindwara, Madhya Pradesh, India', lat: 22.0574, lng: 78.9382, type: 'district' },

  // --- BIHAR DISTRICTS & CITIES ---
  { name: 'Patna', secondary: 'District, Bihar, India', description: 'Patna, Bihar, India', lat: 25.5941, lng: 85.1376, type: 'city' },
  { name: 'Gaya', secondary: 'District, Bihar, India', description: 'Gaya, Bihar, India', lat: 24.7914, lng: 85.0002, type: 'city' },
  { name: 'Bhagalpur', secondary: 'District, Bihar, India', description: 'Bhagalpur, Bihar, India', lat: 25.2425, lng: 86.9842, type: 'city' },
  { name: 'Muzaffarpur', secondary: 'District, Bihar, India', description: 'Muzaffarpur, Bihar, India', lat: 26.1209, lng: 85.3647, type: 'city' },
  { name: 'Darbhanga', secondary: 'District, Bihar, India', description: 'Darbhanga, Bihar, India', lat: 26.1542, lng: 85.8918, type: 'district' },
  { name: 'Purnia', secondary: 'District, Bihar, India', description: 'Purnia, Bihar, India', lat: 25.7771, lng: 87.4753, type: 'district' },
  { name: 'Arrah', secondary: 'Bhojpur District, Bihar, India', description: 'Arrah, Bihar, India', lat: 25.5560, lng: 84.6603, type: 'city' },
  { name: 'Begusarai', secondary: 'District, Bihar, India', description: 'Begusarai, Bihar, India', lat: 25.4182, lng: 86.1272, type: 'district' },
  { name: 'Katihar', secondary: 'District, Bihar, India', description: 'Katihar, Bihar, India', lat: 25.5541, lng: 87.5714, type: 'district' },
  { name: 'Munger', secondary: 'District, Bihar, India', description: 'Munger, Bihar, India', lat: 25.3757, lng: 86.4744, type: 'district' },
  { name: 'Chhapra', secondary: 'Saran District, Bihar, India', description: 'Chhapra, Bihar, India', lat: 25.7796, lng: 84.7499, type: 'city' },
  { name: 'Dharnai', secondary: 'Jehanabad, Bihar, India', description: 'Dharnai, Bihar, India', lat: 25.0489, lng: 84.9810, type: 'village' },

  // --- WEST BENGAL DISTRICTS & CITIES ---
  { name: 'Kolkata', secondary: 'District, West Bengal, India', description: 'Kolkata, West Bengal, India', lat: 22.5726, lng: 88.3639, type: 'city' },
  { name: 'Howrah', secondary: 'District, West Bengal, India', description: 'Howrah, West Bengal, India', lat: 22.5958, lng: 88.2636, type: 'city' },
  { name: 'Durgapur', secondary: 'Paschim Bardhaman, West Bengal, India', description: 'Durgapur, West Bengal, India', lat: 23.5204, lng: 87.3119, type: 'city' },
  { name: 'Asansol', secondary: 'Paschim Bardhaman, West Bengal, India', description: 'Asansol, West Bengal, India', lat: 23.6739, lng: 86.9524, type: 'city' },
  { name: 'Siliguri', secondary: 'Darjeeling, West Bengal, India', description: 'Siliguri, West Bengal, India', lat: 26.7271, lng: 88.3953, type: 'city' },
  { name: 'Darjeeling', secondary: 'District, West Bengal, India', description: 'Darjeeling, West Bengal, India', lat: 27.0410, lng: 88.2663, type: 'district' },
  { name: 'Bardhaman', secondary: 'Purba Bardhaman, West Bengal, India', description: 'Bardhaman, West Bengal, India', lat: 23.2324, lng: 87.8615, type: 'district' },
  { name: 'Malda', secondary: 'District, West Bengal, India', description: 'Malda, West Bengal, India', lat: 25.0108, lng: 88.1411, type: 'district' },
  { name: 'Kharagpur', secondary: 'Paschim Medinipur, West Bengal, India', description: 'Kharagpur, West Bengal, India', lat: 22.3460, lng: 87.2320, type: 'city' },
  { name: 'Haldia', secondary: 'Purba Medinipur, West Bengal, India', description: 'Haldia, West Bengal, India', lat: 22.0667, lng: 88.0667, type: 'city' },

  // --- ODISHA DISTRICTS & CITIES ---
  { name: 'Bhubaneswar', secondary: 'Khordha, Odisha, India', description: 'Bhubaneswar, Odisha, India', lat: 20.2961, lng: 85.8245, type: 'city' },
  { name: 'Cuttack', secondary: 'District, Odisha, India', description: 'Cuttack, Odisha, India', lat: 20.4625, lng: 85.8828, type: 'city' },
  { name: 'Rourkela', secondary: 'Sundargarh, Odisha, India', description: 'Rourkela, Odisha, India', lat: 22.2604, lng: 84.8536, type: 'city' },
  { name: 'Berhampur', secondary: 'Ganjam, Odisha, India', description: 'Berhampur, Odisha, India', lat: 19.3150, lng: 84.7941, type: 'city' },
  { name: 'Sambalpur', secondary: 'District, Odisha, India', description: 'Sambalpur, Odisha, India', lat: 21.4669, lng: 83.9812, type: 'district' },
  { name: 'Puri', secondary: 'District, Odisha, India', description: 'Puri, Odisha, India', lat: 19.8135, lng: 85.8312, type: 'district' },
  { name: 'Balasore', secondary: 'District, Odisha, India', description: 'Balasore, Odisha, India', lat: 21.4934, lng: 86.9135, type: 'district' },

  // --- ASSAM & NORTHEAST CITIES ---
  { name: 'Guwahati', secondary: 'Kamrup Metropolitan, Assam, India', description: 'Guwahati, Assam, India', lat: 26.1445, lng: 91.7362, type: 'city' },
  { name: 'Silchar', secondary: 'Cachar, Assam, India', description: 'Silchar, Assam, India', lat: 24.8333, lng: 92.7789, type: 'city' },
  { name: 'Dibrugarh', secondary: 'District, Assam, India', description: 'Dibrugarh, Assam, India', lat: 27.4728, lng: 94.9120, type: 'district' },
  { name: 'Jorhat', secondary: 'District, Assam, India', description: 'Jorhat, Assam, India', lat: 26.7509, lng: 94.2037, type: 'district' },
  { name: 'Tezpur', secondary: 'Sonitpur, Assam, India', description: 'Tezpur, Assam, India', lat: 26.6528, lng: 92.7926, type: 'town' },
  { name: 'Shillong', secondary: 'East Khasi Hills, Meghalaya, India', description: 'Shillong, Meghalaya, India', lat: 25.5788, lng: 91.8933, type: 'city' },
  { name: 'Agartala', secondary: 'West Tripura, Tripura, India', description: 'Agartala, Tripura, India', lat: 23.8315, lng: 91.2868, type: 'city' },
  { name: 'Imphal', secondary: 'Manipur, India', description: 'Imphal, Manipur, India', lat: 24.8170, lng: 93.9368, type: 'city' },
  { name: 'Aizawl', secondary: 'Mizoram, India', description: 'Aizawl, Mizoram, India', lat: 23.7271, lng: 92.7176, type: 'city' },
  { name: 'Kohima', secondary: 'Nagaland, India', description: 'Kohima, Nagaland, India', lat: 25.6751, lng: 94.1086, type: 'city' },
  { name: 'Dimapur', secondary: 'Nagaland, India', description: 'Dimapur, Nagaland, India', lat: 25.9090, lng: 93.7266, type: 'city' },
  { name: 'Itanagar', secondary: 'Papum Pare, Arunachal Pradesh, India', description: 'Itanagar, Arunachal Pradesh, India', lat: 27.0844, lng: 93.6053, type: 'city' },
  { name: 'Gangtok', secondary: 'Sikkim, India', description: 'Gangtok, Sikkim, India', lat: 27.3389, lng: 88.6065, type: 'city' },

  // --- JHARKHAND & CHHATTISGARH ---
  { name: 'Ranchi', secondary: 'District, Jharkhand, India', description: 'Ranchi, Jharkhand, India', lat: 23.3441, lng: 85.3096, type: 'city' },
  { name: 'Jamshedpur', secondary: 'East Singhbhum, Jharkhand, India', description: 'Jamshedpur, Jharkhand, India', lat: 22.8046, lng: 86.2029, type: 'city' },
  { name: 'Dhanbad', secondary: 'District, Jharkhand, India', description: 'Dhanbad, Jharkhand, India', lat: 23.7957, lng: 86.4304, type: 'city' },
  { name: 'Bokaro', secondary: 'District, Jharkhand, India', description: 'Bokaro, Jharkhand, India', lat: 23.6693, lng: 86.1511, type: 'district' },
  { name: 'Deoghar', secondary: 'District, Jharkhand, India', description: 'Deoghar, Jharkhand, India', lat: 24.4826, lng: 86.7000, type: 'district' },
  { name: 'Raipur', secondary: 'District, Chhattisgarh, India', description: 'Raipur, Chhattisgarh, India', lat: 21.2514, lng: 81.6296, type: 'city' },
  { name: 'Bhilai', secondary: 'Durg, Chhattisgarh, India', description: 'Bhilai, Chhattisgarh, India', lat: 21.1938, lng: 81.3509, type: 'city' },
  { name: 'Bilaspur', secondary: 'District, Chhattisgarh, India', description: 'Bilaspur, Chhattisgarh, India', lat: 22.0797, lng: 82.1409, type: 'city' },
  { name: 'Korba', secondary: 'District, Chhattisgarh, India', description: 'Korba, Chhattisgarh, India', lat: 22.3595, lng: 82.7501, type: 'district' },

  // --- UTTARAKHAND & HIMACHAL PRADESH ---
  { name: 'Dehradun', secondary: 'District, Uttarakhand, India', description: 'Dehradun, Uttarakhand, India', lat: 30.3165, lng: 78.0322, type: 'city' },
  { name: 'Haridwar', secondary: 'District, Uttarakhand, India', description: 'Haridwar, Uttarakhand, India', lat: 29.9457, lng: 78.1642, type: 'district' },
  { name: 'Rishikesh', secondary: 'Dehradun, Uttarakhand, India', description: 'Rishikesh, Uttarakhand, India', lat: 30.0869, lng: 78.2676, type: 'town' },
  { name: 'Nainital', secondary: 'District, Uttarakhand, India', description: 'Nainital, Uttarakhand, India', lat: 29.3919, lng: 79.4542, type: 'district' },
  { name: 'Haldwani', secondary: 'Nainital, Uttarakhand, India', description: 'Haldwani, Uttarakhand, India', lat: 29.2183, lng: 79.5130, type: 'city' },
  { name: 'Almora', secondary: 'District, Uttarakhand, India', description: 'Almora, Uttarakhand, India', lat: 29.5892, lng: 79.6467, type: 'district' },
  { name: 'Ranikhet', secondary: 'Almora, Uttarakhand, India', description: 'Ranikhet, Almora, Uttarakhand, India', lat: 29.6425, lng: 79.4267, type: 'town' },
  { name: 'Shimla', secondary: 'District, Himachal Pradesh, India', description: 'Shimla, Himachal Pradesh, India', lat: 31.1048, lng: 77.1734, type: 'city' },
  { name: 'Dharamshala', secondary: 'Kangra, Himachal Pradesh, India', description: 'Dharamshala, Himachal Pradesh, India', lat: 32.2190, lng: 76.3234, type: 'city' },
  { name: 'Mandi', secondary: 'District, Himachal Pradesh, India', description: 'Mandi, Himachal Pradesh, India', lat: 31.5892, lng: 76.9182, type: 'district' },
  { name: 'Kullu', secondary: 'District, Himachal Pradesh, India', description: 'Kullu, Himachal Pradesh, India', lat: 31.9579, lng: 77.1095, type: 'district' },
  { name: 'Manali', secondary: 'Kullu, Himachal Pradesh, India', description: 'Manali, Himachal Pradesh, India', lat: 32.2432, lng: 77.1892, type: 'town' },

  // --- JAMMU & KASHMIR, LADAKH, GOA ---
  { name: 'Srinagar', secondary: 'District, Jammu and Kashmir, India', description: 'Srinagar, Jammu and Kashmir, India', lat: 34.0837, lng: 74.7973, type: 'city' },
  { name: 'Jammu', secondary: 'District, Jammu and Kashmir, India', description: 'Jammu, Jammu and Kashmir, India', lat: 32.7266, lng: 74.8570, type: 'city' },
  { name: 'Anantnag', secondary: 'District, Jammu and Kashmir, India', description: 'Anantnag, Jammu and Kashmir, India', lat: 33.7311, lng: 75.1522, type: 'district' },
  { name: 'Baramulla', secondary: 'District, Jammu and Kashmir, India', description: 'Baramulla, Jammu and Kashmir, India', lat: 34.1980, lng: 74.3636, type: 'district' },
  { name: 'Leh', secondary: 'District, Ladakh, India', description: 'Leh, Ladakh, India', lat: 34.1526, lng: 77.5771, type: 'district' },
  { name: 'Kargil', secondary: 'District, Ladakh, India', description: 'Kargil, Ladakh, India', lat: 34.5539, lng: 76.1349, type: 'district' },
  { name: 'Panaji', secondary: 'North Goa, Goa, India', description: 'Panaji, Goa, India', lat: 15.4909, lng: 73.8278, type: 'city' },
  { name: 'Margao', secondary: 'South Goa, Goa, India', description: 'Margao, Goa, India', lat: 15.2832, lng: 73.9862, type: 'city' },
  { name: 'Vasco da Gama', secondary: 'South Goa, Goa, India', description: 'Vasco da Gama, Goa, India', lat: 15.3959, lng: 73.8157, type: 'city' },
  { name: 'Mapusa', secondary: 'North Goa, Goa, India', description: 'Mapusa, Goa, India', lat: 15.5937, lng: 73.8142, type: 'town' },
  { name: 'Ponda', secondary: 'North Goa, Goa, India', description: 'Ponda, Goa, India', lat: 15.4026, lng: 74.0150, type: 'town' }
];
